### ISSUE TITLE
Validação de parâmetro

### ISSUE THREAD

**Issue by j040n3t0** [Guilherme-Silveira/elastic-docker#1]
No arquivo "_docker-compose.yml_" na linha 159, tem o seguinte valor "_- agent-data:/usr/share/elastic-agent/state:Zrw_"

Na minha implementação (Debian 11) está dando erro com o parâmetro "_Z_", logo após o "_state_":

```
joaoneto@debian:~/projetos/elastic-docker$ docker-compose up

Creating network "elk" with driver "bridge"
Creating elasticsearch ... done
Creating setup         ... done
Creating logstash          ... done
Creating enterprise-search ... done
Creating kibana            ... done
Creating fleet-server      ... error

ERROR: for fleet-server  Cannot create container for service fleet-server: invalid mode: Zrw
````

Após fazer a remoção do mesmo o compose subiu perfeitamente. Esse parâmetro é realmente necessário?

**Comment by gui-elastic** [comment]
Esse parâmetro tinha sido um teste implementado quando eu estava tomando erro na criação do volume do Fleet Server. Após certas validações, ele realmente provou-se não ser mais necessário. Parâmetro removido!
