### ISSUE TITLE
Falha ao ativar monitoramento sintético

### ISSUE THREAD

**Issue by j040n3t0** [Guilherme-Silveira/elastic-docker#2]
Ao tentar habilitar o monitoramento sintético comecei a tomar o erro abaixo:

```
job could not be initialized: browser monitors cannot be created outside the official elastic docker image
```

Pesquisei bastante na documentação e vi que uma alteração que seria necessário era mudar a imagem do Fleet para **elastic-agent-complete**, com isso eu avancei no monitoramento, digo avancei porque a mensagem de erro mudou. Com a imagem alterada o erro que passou a ser apresentado foi o seguinte:

```
job could not be initialized: script monitors cannot be run as root
```

Como medida de contorno eu removi o parâmetro do user "root" do compose do Fleet, porém após essa alteração o Fleet Server parou se subir e começou a retomar o erro abaixo:

```
Error: preparing STATE_PATH(/usr/share/elastic-agent/state) failed: mkdir /usr/share/elastic-agent/state/data: permission denied
```

Através de algumas pesquisas cheguei a conclusão que esse erro está relacionado a permissão do volume no docker-compose, porque quando eu removo o volume persistente o monitoramento sintético funciona normalmente após as mudanças acima, porém não utilizar um volume persistente faz com que a cada reinicialização do Fleet Server um novo agent seja criado.

Como contornar essa cenário?

**Comment by Guilherme-Silveira** [comment]
Para contornar essa situação, foram feitas modificações no build da imagem do Elastic Agent. O diretório state (montado como volume) precisou ser criado durante o build da imagem e configurado com as permissões corretas para que não seja necessário a utilização do usuário root.

Outra coisa foi a necessidade de mudar a imagem do Elastic Agent para utilizar a elastic-agent-complete. Após feito isso, a função de Synthetics Monitoring passou a funcionar corretamente.
